apiVersion: apps/v1
kind: Deployment
metadata:
  name: modulith-main
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modulith-main
  template:
    metadata:
      labels:
        app: modulith-main
    spec:
      containers:
        - name: modulith-main
          image: whaleplay710/petclinic-modulith-main:3.4.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: petclinic-config
            - secretRef:
                name: petclinic-secrets
          env:
            - name: SPRING_SQL_INIT_MODE
              value: "never"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_AMQP
              value: "DEBUG"
            - name: LOGGING_LEVEL_COM_RABBITMQ_CLIENT
              value: "DEBUG"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis.infra.svc.cluster.local"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: modulith-main
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: modulith-main
  ports:
    - port: 8080
      targetPort: 8080
