apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: whaleplay710/petclinic-notification-service:3.4.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9968
          envFrom:
            - configMapRef:
                name: petclinic-config
            - secretRef:
                name: petclinic-secrets
          env:
            - name: SPRING_SQL_INIT_MODE
              value: "never"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: RABBITMQ_HOST
              value: "rabbitmq.infra.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"

            - name: SPRING_MAIL_HOST
              value: "mailhog.infra.svc.cluster.local"
            - name: SPRING_MAIL_PORT
              value: "1025"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "false"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "false"         
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 9968
      targetPort: 9968
